name: PSScriptAnalyzer Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  analyze:
    
    name: PSScriptAnalyzer Scan
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout code
        uses: actions/checkout@v2

      - name: PowerShell Module Cache
        uses: potatoqualitee/psmodulecache@v4.5
        with:
          # This doesn't update modules, so might wanto to pin version later to know which we use like ConverToSARIF:1.0.0
          modules-to-cache: PSScriptAnalyzer, ConvertToSARIF
          allow-prerelease: false

      # Not using microsoft/psscriptanalyzer-action@v1.0 because we're missing psm1 in src and need to exclude generated ps1xml
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Import-Module ConvertToSARIF -Force
          
          Get-ChildItem -Path ./src/ -Filter *.ps1 -Recurse |
          Invoke-ScriptAnalyzer -Settings ./PSScriptAnalyzerSettings.psd1 |
          ConvertTo-SARIF -FilePath results.sarif

      # Upload the SARIF file generated in the previous step
      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
